services:
  postgres:
    image: postgres:12.17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Pg#123
      - POSTGRES_USER=taskflowuser
      - POSTGRES_DB=taskflow
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - taskflow-network
  taskflow:
    image: thatianaliz/taskflow:01-dockerfile-manual-v2
    ports: 
      - 3000:3000
    environment:
      - DB_NAME=taskflow
      - DB_USER=taskflowuser
      - DB_PASSWORD=Pg#123
      - DB_HOST=postgres
    networks:
      - taskflow-network

volumes:
  postgres-data:
    name: postgres-data
    external: true

networks:
  taskflow-network:
    name: taskflow-network
    driver: bridge
